edition = "2021"

max_width = 100
hard_tabs = false
tab_spaces = 4

use_small_heuristics = "Default"

newline_style = "Unix"

reorder_imports = true
reorder_modules = true

imports_granularity = "Crate"
group_imports = "StdExternalCrate"

format_code_in_doc_comments = true
normalize_doc_attributes = true

wrap_comments = true
comment_width = 100

match_block_trailing_comma = true
